const UserList = [
    {
      id: 1,
      username: "Muhammad Ripaldi",
      email: "ripaldi@student.ibik.ac.id",
      password: "ripaldi",
    },
    {
      id: 2,
      username: "Satrio Ardia ",
      email: "satrio@student.ibik.ac.id",
      password: "satrio",
    },
    {
        id: 3,
        username: "Fakhri Akmal",
        email: "fakhri@student.ibik.ac.id",
        password: "fakhri",
      },
      {
        id: 4,
        username: "Dandi Hendika",
        email: "dandi@student.ibik.ac.id",
        password: "dandi",
      },
      {
        id: 5,
        username: "Muhamad Gymnastiar",
        email: "gymnastiar@student.ibik.ac.id",
        password: "gymnastiar",
      },
      {
        id: 6,
        username: "Chandradinata",
        email: "chandra@student.ibik.ac.id",
        password: "chandra",
      },
      {
        id: 7,
        username: "Reyhan Javier Rachman",
        email: "reyhan@student.ibik.ac.id",
        password: "reyhan",
      },
      {
        id: 8,
        username: "Ikram Nurhadi Damansiz",
        email: "ikram@student.ibik.ac.id",
        password: "ikram",
      },
      {
        id: 9,
        username: "Muhammad Fadlan Syakur",
        email: "fadlan@student.ibik.ac.id",
        password: "fadlan",
      },
      {
        id: 10,
        username: "Siti Sarah",
        email: "sarah@student.ibik.ac.id",
        password: "sarah",
      },
      {
        id: 11,
        username: "Muhammad Faadihilah",
        email: "faadihilah@student.ibik.ac.id",
        password: "faadihilah",
      },
      {
        id: 12,
        username: "Fikri Maulana Iskandar",
        email: "fikri@student.ibik.ac.id",
        password: "fikri",
      },
      {
        id: 13,
        username: "Julius Taslim",
        email: "julius@student.ibik.ac.id",
        password: "julius",
      },
      {
        id: 14,
        username: "Carlos Immanuel Tampubolon",
        email: "carlos@student.ibik.ac.id",
        password: "carlos",
      },
      {
        id: 15,
        username: "Putri Agatha Naomi",
        email: "putri@student.ibik.ac.id",
        password: "putri",
      },
      {
        id: 16,
        username: "Syahid Muhammad Zubeir",
        email: "syahid@student.ibik.ac.id",
        password: "syahid",
      },
      {
        id: 17,
        username: "Sandry Chandra Putra",
        email: "sandry@student.ibik.ac.id",
        password: "sandry",
      },
      {
        id: 18,
        username: "Agnes Abigael Wijaya",
        email: "agnes@student.ibik.ac.id",
        password: "agnes",
      },
      {
        id: 19,
        username: "Dandi Hendika",
        email: "dandi@student.ibik.ac.id",
        password: "dandi",
      },
      {
        id: 20,
        username: "Reguel Dos Santos",
        email: "reguel@student.ibik.ac.id",
        password: "reguel",
      },
      {
        id: 21,
        username: "Mohamad Iqbal Fahmi",
        email: "iqbal@student.ibik.ac.id",
        password: "iqbal",
      },
      {
        id: 22,
        username: "Davi Aldela",
        email: "davi@student.ibik.ac.id",
        password: "davi",
      },
      {
        id: 23,
        username: "Aron Alexanda",
        email: "aron@student.ibik.ac.id",
        password: "aron",
      },
      {
        id: 24,
        username: "Zaqi Apriyansyah",
        email: "zaqi@student.ibik.ac.id",
        password: "zaqi",
      },
      {
        id: 25,
        username: "Febri Tri Purnama",
        email: "febri@student.ibik.ac.id",
        password: "febri",
      },
      {
        id: 26,
        username: "Reymanda Putra",
        email: "reymanda@student.ibik.ac.id",
        password: "reymanda",
      },
  ];

  export { UserList }